version: '2'
services:
  subjektiv_news-app:
    image: subjektiv_news
    environment:
      - _JAVA_OPTIONS=-Xmx512m -Xms256m
      - SPRING_PROFILES_ACTIVE=prod,swagger
      - MANAGEMENT_METRICS_EXPORT_PROMETHEUS_ENABLED=true
      - SPRING_DATASOURCE_URL=jdbc:postgresql://subjektiv_news-postgresql:5432/subjektiv_news
      - JHIPSTER_SLEEP=30 # gives time for other services to boot before the application
    ports:
      - 8080:8080
  subjektiv_news-postgresql:
    extends:
      file: postgresql.yml
      service: subjektiv_news-postgresql
